### PR TITLE
RunMainLoop: Don't use Go heap for MSG

### LINKED ISSUE #1083: [v2] Windows: random access violations during DispatchMessage
**Description**
We have seen several reports from users with AccessViolations during `DispatchMessage/GetMessage` in `RunMainLoop`

```
Exception 0xc0000005 0x0 0x7ff811db0998 0x7ff911b3d98c
PC=0x7ff911b3d98c
runtime.cgocall(0x86060, 0x9888a0)
    /usr/local/go/src/runtime/cgocall.go:156 +0x4a fp=0xc000115af8 sp=0xc000115ac0 pc=0x2404a
syscall.Syscall(0x7ff967eb0bf0, 0x1, 0xc00037c0f0, 0x0, 0x0)
    /usr/local/go/src/runtime/syscall_windows.go:483 +0xf4 fp=0xc000115b30 sp=0xc000115af8 pc=0x80c74
syscall.Syscall(0x0, 0x100, 0x10, 0x9, 0xc000115be8)
    <autogenerated>:1 +0x2b fp=0xc000115b80 sp=0xc000115b30 pc=0x86f4b
syscall.(*Proc).Call(0x2d507, {0xc00038c020, 0x488c00, 0x82401})
    /usr/local/go/src/syscall/dll_windows.go:183 +0xc6 fp=0xc000115c70 sp=0xc000115b80 pc=0x9e9e6
syscall.(*LazyProc).Call(0xc000188f00, {0xc00038c020, 0x1, 0x1})
    /usr/local/go/src/syscall/dll_windows.go:340 +0x50 fp=0xc000115ca0 sp=0xc000115c70 pc=0x9fd50
github.com/leaanthony/winc/w32.DispatchMessage(...)
    /builds/app/vendor/github.com/leaanthony/winc/w32/user32.go:326
github.com/leaanthony/winc.RunMainLoop()
...
```

**To Reproduce**
Steps to reproduce the behaviour: This is very hard, because it only manifests randomly. Fortunatelay we had one user on whose machine it happened during every startup of the Application. Apart from this user, we only had panics which occurred randomly. 

**Additional context**
After some investigation I've found several Go projects, which also run Windows MessageLoops, to have reports of similar AccessViolations during `DispatchMessage/GetMessage`, e.g. `lxn/walk` or `go-sciter`. Many thanks to @zx2c4 who created a PR for lxn/walk#493 which fixed the issue there. It turned out it also fixed our issue for that user.

I'm going to provide a PR for `winc` which will introduce the same fix as in lxn/walk#493.

### PR DESCRIPTION
**Pull request by stffabi**
This fixes random AccessViolations during Dispatch/GetMessage.

See https://github.com/lxn/walk/pull/493

Fix wailsapp/wails#1083

### CODE REVIEW

**Comment by leaanthony** [comment]
That's really quite odd! I wonder why this is the case. It seems the fix has worked for others so let's give it a go. Thanks again for being on top of all the really hard Windows issues 💯 👍

**Comment by stffabi** [comment]
Yes It's really strange and I also wonder why this is the case. But I was happy that at least for this users it happened all the time. So I could at least make sure the workaround fixes the issue.

Yeah, Windows Api things bring always some surprises. We have distributed our app to a broader Windows customer base and apart from this we had no serious issues.

**Comment by leaanthony** [comment]
@stffabi - I think your other PR may need updating again after this merge?

**Comment by stffabi** [comment]
PR has been updated.

**Pull request merged**
